### ISSUE TITLE
Poster Mode

### ISSUE THREAD

**Issue by JackRobbers** [igembitsgoa/igem-wikisync#5]
Hi Pranav, I noticed you updated the wikisync action to have a poster mode option, but couldn't find any changes on this repo relating to it. If you need a hand getting it working I'm happy to help out.

**Comment by ballaneypranav** [comment]
Hi Jack, thank you for offering to help with WikiSync. I had updated it to work with iGEM posters a few days ago ([prerelease](https://pypi.org/project/igem-wikisync/1.1.0a0/)), but I didn't have a chance to test it until now. I've done that now and it works alright. Here is the [latest release](https://pypi.org/project/igem-wikisync/1.1.0a1/).

I will soon update the docs as well. Meanwhile, you can take a look at [this](https://github.com/igembitsgoa/poster/blob/249b3c2c964b29779bb7e8f6344ff8ae0a0cd301/.github/workflows/push.yml#L86) for an example of how to use the poster mode. 

Basically, in Poster mode, WikiSync allows you to upload only one HTML file, and no CSS/JS files. You'll have to manually make sure that this HTML file contains all your required CSS and JS. For an example of that, see [here](https://github.com/igembitsgoa/poster/blob/master/utils/postprocess.py). Besides, it renames everything in `assets` from `filename.ext` to `T--TeamName--Poster_filename.ext`. It also prepends the iGEM `{{ Poster }}` template to the HTML file. 

There is currently no way to upload through WikiSync without appending the `{{ Poster }}` template. Please feel free to work on that if you would like to.
